package com.cinenotes.domain;

public enum AuditAction {
    LOGIN,
    REGISTER,
    TITLE_IMPORTED,
    TITLE_CREATED,
    TITLE_UPDATED,
    TITLE_DELETED,
    REVIEW_CREATED,
    REVIEW_UPDATED,
    REVIEW_DELETED,
    REVIEW_MODERATED,
    REVIEW_HIDDEN,
    REVIEW_RESTORED,
    WATCHLIST_UPDATED,
    WATCH_LOG_CREATED,
    GENRE_CREATED,
    GENRE_UPDATED,
    GENRE_DELETED,
    MOOD_TAG_CREATED,
    MOOD_TAG_UPDATED,
    MOOD_TAG_DELETED,
    USER_ROLE_UPDATED,
    USER_ACTIVATED,
    USER_DEACTIVATED
}
